name: ww_reactor
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_scale_tap: ^1.0.5
  bubble_chart: ^0.4.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite: ^2.2.0
  path_provider: ^2.0.11
  http: ^0.13.0

  




 # The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Asap
      fonts:
        - asset: fonts/Asap-Regular.ttf
        - asset: fonts/Asap-Italic.ttf
          style: italic
